### ISSUE TITLE
Change ET-Client-Name policy towards Entur api

### ISSUE THREAD

**Issue by andtry** [marhoy/flask-entur-avgangstider#2]
Hi,

Great so see you are using the Entur Journey planner api in your service. We do however see that your create a unique ET-Client-Name pr. line you set up in your service. Typically we see hundreds of "flask - avgangstider_xxx" names in our logging. This creates a lot of noice in our operations tools. Could you please consolidate your use of ET-Client-Name into one ET-Client-name pr. deployment.

Would appreciate if you could fix this!

If you have any further questions please contact us at kollektivdata@entur.org

/Andreas

**Comment by marhoy** [comment]
Sorry about the log-spam :)
The ET-Client-name is now changed to flask-entur-avgangstider-$hostname, so it will be unique per deployment.

Code and docker image is updated.

Martin
